# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 715755ea92968235f6858b003cce00de3f6c89d5dcbd867fbaf0641d76ac40b978b3a628e7fa8aec84b53f27539cea691ea140e03c74605ec1404fcc1f646e39

test:
  secret_key_base: 8794b6ac2388fe9f7cbbd580297b7f0f326e0cc38a7a0625e3c7798ba73794cc4e9807f12d8a3979c08261ec493b7dacab3671aed570d578510301c024bc75d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
